layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 8
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: sirekaushal
  # hackerrank: your_username
  instagram: sirekaushal
  keybase: sirekaushal
  linkedin: sirekaushal
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: professorpandit
  twitter: sirekaushal
  # unsplash: your_username
  # vk: your_username
  website: https://professorpandit.github.io
  # youtube: your_username

topics:
  - name: Documentation
    web_url: https://github.com/topics/documentation

  - name: Node.js
    web_url: https://github.com/topics/nodejs

  - name: Command Line Interface
    web_url: https://github.com/topics/cli

  - name: LaTeX
    web_url: https://github.com/topics/latex
